name: Build and Run Docker Compose

on: [ push, pull_request]

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Images
        run: docker compose build
        shell: bash
