name: Build and Run Docker Compose

on: [ push, pull_request]
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker-compose

      - name: Run Docker Compose via Makefile
        run: make run
        shell: bash